### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'VaadinClassicEditor')

### ISSUE THREAD

**Issue by JasonTheDynamite** [wontlost-ltd/vaadin-litelement-ckeditor#43]
CkEditor does not show and does not work.

vaadin version: 23.2.6
`implementation 'com.wontlost:ckeditor-vaadin:3.2.1'`

<img width="480" alt="image" src="https://user-images.githubusercontent.com/18309065/220424424-e7b8488b-a148-4cb6-987b-c84ab867d93a.png">

How to fix this ?

**Comment by stefanuebe** [comment]
Has this been solved?

**Comment by eroself** [comment]
May relate to applicatoin.properties
`vaadin.whitelisted-packages = com.wontlost`

**Comment by johnfilo-kmart** [comment]
I'm facing this issue. I have deployed my vaadin maven webapp in production mode, and I get this error and the editor won;t display. When I run this locally in dev mode, it works just fine.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'VaadinClassicEditor')
    at $D.getEditorByType (chunk-81974d568f74e077417b65f67b314345b2acc58bc9aba626ea18aab8043cf2ad-d3b759b7.js:7757:38509)
    at $D.createEditor (chunk-81974d568f74e077417b65f67b314345b2acc58bc9aba626ea18aab8043cf2ad-d3b759b7.js:7757:39091)
    at $D.firstUpdated (chunk-81974d568f74e077417b65f67b314345b2acc58bc9aba626ea18aab8043cf2ad-d3b759b7.js:7757:38221)
    at $D._$AE (indexhtml-094c3aa6.js:9:5122)
    at $D.performUpdate (indexhtml-094c3aa6.js:9:4927)
    at $D.scheduleUpdate (indexhtml-094c3aa6.js:9:4514)
    at $D._$Ej (indexhtml-094c3aa6.js:9:4422)
```

I have the following in my application.properties file:

server.port=5000
vaadin.whitelisted-packages = com.wontlost

any ideas?

**Comment by Osiris-Team** [comment]
Having the same issue.

Forgot to add vaadin.whitelisted-packages = com.wontlost
however after adding still getting the same issue.

Default latest vaadin starter project with gradle.

**Comment by redsilver** [comment]
Same problem here without springboot.
